INSERT INTO canal (nome, sigla) VALUES
('Rede Globo', 'Globo'),
('Sistema Brasileiro de Televisão', 'SBT'),
('RecordTV', 'Record'),
('Rede Bandeirantes', 'Band'),
('RedeTV!', 'RedeTV'),
('TV Cultura', 'Cultura'),
('TV Brasil', 'TVB'),
('Canal Futura', 'Futura'),
('Esporte Interativo', 'EI'),
('Fox Sports', 'Fox Sports'),
('HBO Brasil', 'HBO'),
('CNN Brasil', 'CNN'),
('Disney Channel', 'Disney'),
('Cartoon Network', 'CN'),
('National Geographic Channel', 'NatGeo'),
('Discovery Channel', 'Discovery'),
('MTV Brasil', 'MTV'),
('Nickelodeon Brasil', 'Nick'),
('Telecine', 'Telecine'),
('History Channel', 'History');

insert into premio (premios) values 
('Academy Awards'), ('Cannes Film Festival'), ('Golden Globe Awards'), ('British Academy of Film and Television Arts'), ('Venice Film Festival'),
('Berlin International Film Festival'), ('Screen Actors Guild Awards'), ("Critics' Choice Movie Awards"), ('Independent Spirit Awards'), ('Sundance Film Festival'),
('European Film Awards'), ('Asian Film Awards'), ('Annie Awards'), ('Satellite Awards'), ('MTV Movie & TV Awards'), ('Gotham Independent Film Awards'),
('Hollywood Film Awards'), ('International Emmy Awards'), ('Ariel Awards'), ('Genie Awards'), ('Jutra Awards'), ('Premios Platino del Cine Iberoamericano'),
('Premios Fénix'), ('Grande Prêmio do Cinema Brasileiro'), ('Academia de las Artes y las Ciencias Cinematográficas de Argentina'), ('Premios Cóndor de Plata'),
('César Awards'), ('Goya Awards'), ('David di Donatello Awards'), ('German Film Awards'), ('Magritte Awards'), ('Bodil Awards'), ('Robert Awards'), ('Guldbagge Awards'),
('Amanda Awards'), ('Irish Film & Television Awards'), ('Swiss Film Award'), ('Golden Orange Awards'), ('Blue Dragon Film Awards'), ('Golden Bell Awards'),
('Nika Awards'), ('Polish Film Awards'), ('Luxembourg Film Prize'), ('Filmfare Awards'), ('National Film Awards'), ('Japan Academy Prize'), ('Grand Bell Awards'),
('Golden Horse Awards'), ('Hong Kong Film Awards'), ('Fajr International Film Festival'), ('Asia Pacific Screen Awards'), ('Africa Movie Academy Awards'),
("Africa Magic Viewers' Choice Awards"), ('Panafrican Film and Television Festival of Ouagadougou'), ('Australian Academy of Cinema and Television Arts Awards'),
('New Zealand Film Awards'), ('Saturn Awards'), ('Hugo Awards'), ('Razzie Awards'), ("Kids' Choice Awards"), ('Teen Choice Awards'), ("Women's Image Network Awards"),
('Toronto International Film Festival'), ('South by Southwest'), ('Tribeca Film Festival'), ('Locarno Film Festival'), ('San Sebastián International Film Festival'),
('Karlovy Vary International Film Festival'), ('Rotterdam International Film Festival'), ('Mar del Plata Film Festival'), ('Busan International Film Festival'),
('International Documentary Association Awards'), ('Cinema Eye Honors'), ('DocAviv Film Festival Awards'), ('Sheffield Doc/Fest Awards');

INSERT INTO categoria (nome_categoria) VALUES
('Ação'), ('Aventura'), ('Animação'), 
('Biografia'), ('Comédia'), ('Crime'), 
('Documentário'), ('Drama'), ('Épico'), 
('Família'), ('Fantasia'), ('Faroeste'), 
('Ficção Científica'), ('Guerra'), ('Histórico'), 
('Mistério'), ('Musical'), ('Policial'), 
('Romance'), ('Suspense'), ('Terror'), 
('Thriller'), ('Noir'), ('Esporte'), 
('Tribunal'), ('Espionagem'), ('Artes Marciais'), 
('Independente'), ('Experimental'), ('LGBTQ+'), 
('Fantasia Urbana'), ('Road Movie'), ('Pós-apocalíptico'), 
('Super-heróis'), ('Religioso'), ('Zumbi'), 
('Vampiro'), ('Monstros'), ('Antológico'), 
('Dança'), ('Aventura Espacial'), ('Natal'), 
('Cult'), ('Psicológico'), ('Social');

INSERT INTO diretor (nome_diretor) VALUES
('Steven Spielberg'), ('Martin Scorsese'), ('Quentin Tarantino'), 
('Christopher Nolan'), ('David Fincher'), ('James Cameron'), 
('Ridley Scott'), ('Tim Burton'), ('Peter Jackson'), 
('Clint Eastwood'), ('Woody Allen'), ('Spike Lee'), 
('Francis Ford Coppola'),('Francis Lawrence'), ('Alfred Hitchcock'), ('Stanley Kubrick'), 
('George Lucas'), ('Robert Zemeckis'),('Zack Snyder'), ('Michael Bay'), 
('Oliver Stone'), ('John Carpenter'), ('Brian De Palma'), 
('Wes Craven'), ('John Hughes'), ('John Landis'), ('Joss Whedon'),
('J.J. Abrams'), ('Sam Raimi'), ('Joel Coen'), ('Ethan Coen'), 
('Paul Thomas Anderson'), ('David Lynch'), ('Darren Aronofsky'), 
('Roman Polanski'), ('Pedro Almodóvar'), ('Lars von Trier'), 
('Ingmar Bergman'), ('Federico Fellini'), ('Akira Kurosawa'), 
('Hayao Miyazaki'), ('Sergio Leone'), ('Jean-Luc Godard'), 
('François Truffaut'), ('Michelangelo Antonioni'), ('Bernardo Bertolucci'), 
('Luchino Visconti'), ('Vittorio De Sica'), ('Roberto Rossellini'), 
('Fritz Lang'), ('Billy Wilder'), ('John Huston'), ('Howard Hawks'), 
('Orson Welles'), ('Frank Capra'), ('George Cukor'), ('William Wyler'), 
('John Ford'), ('David Lean'), ('Michael Curtiz'), ('Victor Fleming'), 
('Cecil B. DeMille'), ('King Vidor'), ('George Stevens'), ('Fred Zinnemann'), 
('Elia Kazan'), ('Joseph L. Mankiewicz'), ('Vincente Minnelli'), ('Robert Wise'), 
('Billy Wilder'), ('Delbert Mann'), ('Jerome Robbins'), ('Robert Wise'), 
('Tony Richardson'), ('David Lean'), ('George Cukor'), ('Fred Zinnemann'), 
('Mike Nichols'), ('Carol Reed'), ('John Schlesinger'), ('Franklin J. Schaffner'), 
('William Friedkin'), ('Milos Forman'), ('Robert Redford'), ('Warren Beatty'), 
('Richard Attenborough'), ('Sydney Pollack'), ('Oliver Stone'), ('Kevin Costner'), 
('Jonathan Demme'), ('Clint Eastwood'), ('Mel Gibson'), ('Ron Howard'), 
('Anthony Minghella'), ('Steven Spielberg'), ('Sam Mendes'), ('Steven Soderbergh'), 
('Roman Polanski'), ('Peter Jackson'), ('Clint Eastwood'), ('Martin Scorsese'), 
('Danny Boyle'), ('Kathryn Bigelow'), ('Tom Hooper'), ('Michel Hazanavicius'), 
('Ang Lee'), ('Alfonso Cuarón'), ('Alejandro González Iñárritu'), ('Damien Chazelle'), 
('Guillermo del Toro'), ('Bong Joon-ho'), ('Chloé Zhao'), ('Spike Lee'), 
('David Lynch'), ('David Cronenberg'), ('David O. Russell'), ('David Ayer'), 
('David Twohy'), ('David Gordon Green'), ('David Dobkin'), ('David Koepp'), 
('David Mamet'), ('David Lean'), ('David Fincher'), ('David Zucker'), 
('David Wain'), ('David Schwimmer'),
('John McTiernan'), ('John Woo'), ('John Ford'), 
('John Huston'), ('John Sturges'), ('John Frankenheimer'), 
('John Schlesinger'), ('John Waters'), ('John Singleton'), 
('John Sayles'), ('John Lasseter'), ('John Boorman'), 
('John Milius'), ('John Badham'), ('John G. Avildsen'), 
('John Glen');