
INSERT INTO canal (nome, sigla, logo_canal) VALUES
('Rede Globo', 'Globo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1S3WHuIf9kmExAfpJDGzxYTMuBLgdlczp-w&s'),
('Sistema Brasileiro de Televisão', 'SBT', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcVYPc-pELbp8t_0EhGtRFsSj1gXPMQWJgwA&s'),
('RecordTV', 'Record', 'https://play-lh.googleusercontent.com/86YxRYXi1bikmEQInrLFY7913Ng0xgzwZPuXU5k7NWnePoxX4E6UxMK8I5axLJZqWsDb=w240-h480-rw'),
('Rede Bandeirantes', 'Band', 'https://cdn.worldvectorlogo.com/logos/band-1.svg'),
('RedeTV!', 'RedeTV', 'https://pbs.twimg.com/media/FywWpO1X0AAfD3B.jpg:large'),
('TV Cultura', 'Cultura', 'https://upload.wikimedia.org/wikipedia/commons/8/82/Cultura_logo_2013.svg'),
('TV Brasil', 'TVB', 'https://yt3.googleusercontent.com/fs6EI0tEgITiQzy3j5nXhp6hv9KBWYPMjqJTbPdH6ogzGnEI2P-lF9oBMlbku7bp1VXxcy8cxw=s176-c-k-c0x00ffffff-no-rj-mo'),
('Canal Futura', 'Futura', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLorEDMiv4WNKxoCRPxaPWfYPvc5ntwWgjVDKyRRbwVylAlOTLi0KyacUcjOfU6x8EZCY&usqp=CAU'),
('Esporte Interativo', 'EI', 'https://upload.wikimedia.org/wikipedia/commons/1/19/LOGO_EI-2.jpg'),
('Fox Sports', 'Fox Sports', 'https://logowik.com/content/uploads/images/fox-sports3529.jpg'),
('HBO Brasil', 'HBO', 'https://logowik.com/content/uploads/images/hbo.jpg'),
('CNN Brasil', 'CNN', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgT-R52bE5nFi11FvXv3Er0ADTmXuBd3ieeQ&s'),
('MTV Brasil', 'MTV', 'https://cdn.dribbble.com/users/174209/screenshots/1465961/media/1956c5abb6840358546e32cf3298057a.jpg?resize=400x300&vertical=center'),
('Telecine', 'Telecine', 'https://gkpb.com.br/wp-content/uploads/2019/07/novo-logo-telecine-seu-momento-cinema-versao-negativa-1024x1024.jpg');



INSERT INTO categoria (nome_categoria) VALUES
('Ação'), ('Aventura'), ('Animação'), 
('Biografia'), ('Comédia'), ('Crime'), 
('Documentário'), ('Drama'), ('Épico'), 
('Família'), ('Fantasia'), ('Faroeste'), 
('Ficção Científica'), ('Guerra'), ('Histórico'), 
('Mistério'), ('Musical'), ('Policial'), 
('Romance'), ('Suspense'), ('Terror'), 
('Thriller'), ('Noir'), ('Esporte'), 
('Tribunal'), ('Espionagem'), ('Artes Marciais'), 
('Independente'), ('Experimental'), ('LGBTQ+'), 
('Fantasia Urbana'), ('Road Movie'), ('Pós-apocalíptico'), 
('Super-heróis'), ('Religioso'), ('Zumbi'), 
('Vampiro'), ('Monstros'), ('Antológico'), 
('Dança'), ('Aventura Espacial'), ('Natal'), 
('Cult'), ('Psicológico'), ('Social');

INSERT INTO diretor (nome_diretor) VALUES
('Steven Spielberg'), ('Quentin Tarantino'), 
('Christopher Nolan'), ('David Fincher'), ('James Cameron'), 
('Ridley Scott'), ('Tim Burton'), ('Peter Jackson'), 
('Clint Eastwood'), ('Woody Allen'), ('Spike Lee'), 
('Francis Ford Coppola'),('Francis Lawrence'), ('Alfred Hitchcock'), ('Stanley Kubrick'), 
('George Lucas'), ('Robert Zemeckis'),('Zack Snyder'), ('Michael Bay'), 
('Oliver Stone'), ('John Carpenter'), ('Brian De Palma'), 
('Wes Craven'), ('John Hughes'), ('John Landis'), ('Joss Whedon'),
('J.J. Abrams'), ('Sam Raimi'), ('Joel Coen'), ('Ethan Coen'), 
('Paul Thomas Anderson'), ('David Lynch'), ('Darren Aronofsky'), 
('Pedro Almodóvar'), ('Lars von Trier'), 
('Ingmar Bergman'), ('Federico Fellini'), ('Akira Kurosawa'), 
('Hayao Miyazaki'), ('Sergio Leone'), ('Jean-Luc Godard'), 
('François Truffaut'), ('Michelangelo Antonioni'), ('Bernardo Bertolucci'), 
('Luchino Visconti'), ('Vittorio De Sica'), ('Roberto Rossellini'), 
('Fritz Lang'), ('John Huston'), ('Howard Hawks'), 
('Orson Welles'), ('Frank Capra'), ('George Cukor'), ('William Wyler'), 
('John Ford'), ('Michael Curtiz'), ('Victor Fleming'), 
('Cecil B. DeMille'), ('King Vidor'), ('George Stevens'), ('Fred Zinnemann'), 
('Elia Kazan'), ('Joseph L. Mankiewicz'), ('Vincente Minnelli'), 
('Billy Wilder'), ('Delbert Mann'), ('Jerome Robbins'), ('Robert Wise'), 
('Tony Richardson'), 
('Mike Nichols'), ('Carol Reed'), ('Franklin J. Schaffner'), 
('William Friedkin'), ('Milos Forman'), ('Robert Redford'), ('Warren Beatty'), 
('Richard Attenborough'), ('Sydney Pollack'), ('Kevin Costner'), 
('Jonathan Demme'), ('Mel Gibson'), ('Ron Howard'), 
('Anthony Minghella'), ('Sam Mendes'), ('Steven Soderbergh'), 
('Danny Boyle'), ('Kathryn Bigelow'), ('Tom Hooper'), ('Michel Hazanavicius'), 
('Ang Lee'), ('Alfonso Cuarón'), ('Alejandro González Iñárritu'), ('Damien Chazelle'), 
('Guillermo del Toro'), ('Bong Joon-ho'), ('Chloé Zhao'), 
('David Cronenberg'), ('David O. Russell'), ('David Ayer'), 
('David Twohy'), ('David Gordon Green'), ('David Dobkin'), ('David Koepp'), 
('David Mamet'),('David Zucker'), 
('David Wain'), ('David Schwimmer'),
('John McTiernan'), ('John Woo'), 
('John Sturges'), ('John Frankenheimer'), 
('John Waters'), ('John Singleton'), 
('John Sayles'), ('John Lasseter'), ('John Boorman'), 
('John Milius'), ('John Badham'), ('John G. Avildsen'), 
('John Glen'), ('Lana Wachowski'), ('Frank Darabont'),
('Adrian Molina'), ('George Miller'), ('Wes Anderson'),
('Byron Howard');


INSERT INTO filme(titulo_original, titulo_brasil, sinopse, ano_lancamento, poster_url, pas_origem, duracao, id_diretor, class_indicativo) VALUES
('Inside Out 2', 'Divertida Mente 2', 'Com um salto temporal, Riley se encontra mais velha, passando pela tão temida adolescência. Junto com o amadurecimento, a sala de controle também está passando por uma adaptação para dar lugar a algo totalmente inesperado: novas emoções. As já conhecidas, Alegria, Raiva, Medo, Nojinho e Tristeza não têm certeza de como se sentir quando novos inquilinos chegam ao local.', 2024, 'https://s2-gshow.glbimg.com/dNCoZiC_keIRzhEw4UmfREovP9g=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_e84042ef78cb4708aeebdf1c68c6cbd6/internal_photos/bs/2024/Y/Q/t3mVQNQu6qdzvBjCthUg/divertidamente-divertida-mente-ansiedade-alegria-inside-out-filme-pixar.jpg', 'EUA', 96, 1, 'Livre'),
('Interstellar', 'Interestelar', 'As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand, Jenkins e Doyle, ele seguirá em busca de um novo lar.', 2014, 'https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/aa5b9295-8f9c-44f5-809b-3f2b84badfbf/8a7dd34b09c9c25336a3d850d4c431455e1aaaf0.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom', 'EUA', 169, 4, '10'),
('Inception', 'A Origem', 'Dom Cobb é um ladrão habilidoso, o melhor na perigosa arte da extração, que rouba segredos valiosos do fundo do subconsciente durante o estado de sonho, quando a mente está mais vulnerável. A rara habilidade de Cobb fez dele um cobiçado jogador nesse traiçoeiro novo mundo de espionagem corporativa, mas também fez dele um fugitivo internacional e custou-lhe tudo o que já amou.', 2010, 'https://i0.wp.com/ovicio.com.br/wp-content/uploads/2020/08/20200802-filme-a-origem.jpg', 'EUA', 148, 4, '12'),
('The Matrix', 'Matrix', 'Um jovem programador é atormentado por estranhos pesadelos nos quais se vê conectado por cabos a um imenso sistema de computadores do futuro. Em todas as noites, ele acorda com a mesma pergunta: o que é a Matrix? A resposta o leva a um submundo onde ele descobre que a vida que conhece é uma ilusão criada por uma inteligência cibernética, para que os humanos nunca percebam a verdade.', 1999, 'https://rollingstone.com.br/media/uploads/carrie-anne_moss_e_keanu_reeves_em_matrix_foto_divulgacao.jpg', 'EUA', 136, 121, '16'),
('Parasite', 'Parasita', 'Toda a família de Ki-taek está desempregada, vivendo em um porão sujo e apertado. Um dia, seu filho consegue um emprego como tutor de uma garota rica, iniciando uma série de eventos que colocam as duas famílias em rota de colisão.', 2019, 'https://diplomatique.org.br/wp-content/uploads/2020/01/filme-parasita.jpg', 'Coreia do Sul', 132, 95, '16'),
('The Godfather', 'O Poderoso Chefão', 'A saga da família Corleone, uma das mais poderosas da máfia italiana nos Estados Unidos, liderada por Don Vito Corleone. Quando o patriarca da família é quase morto, seu filho Michael assume o controle dos negócios, iniciando uma violenta guerra entre as famílias mafiosas.', 1972, 'https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fb9c272e7-4e43-4b20-9407-de4e14638a34_1000x563.jpeg', 'EUA', 175, 12, '18'),
('The Shawshank Redemption', 'Um Sonho de Liberdade', 'Dois homens presos desenvolvem um vínculo ao longo de vários anos, encontrando consolo e redenção através de atos de decência comum.', 1994, 'https://media.gazetadopovo.com.br/2022/04/15182712/usdl.jpg', 'EUA', 142, 122, '16'),
('Pulp Fiction', 'Pulp Fiction: Tempo de Violência', 'As vidas de dois assassinos de aluguel, um boxeador, a esposa de um gângster e dois bandidos se entrelaçam em quatro histórias de violência e redenção.', 1994, 'https://m.media-amazon.com/images/S/pv-target-images/c55624c14560ba8f1604fcb95f590d62889c476a78d0ccf6de60feda54237f6a._SX1080_FMjpg_.jpg', 'EUA', 154, 2, '18'),
('The Dark Knight', 'Batman: O Cavaleiro das Trevas', 'Quando o Coringa emerge como uma nova ameaça, Batman deve aceitar um dos maiores testes psicológicos e físicos de sua capacidade de lutar contra a injustiça.', 2008, 'https://m.media-amazon.com/images/I/51k0qa6q0oL._AC_.jpg', 'EUA', 152, 3, '12'),
('Forrest Gump', 'Forrest Gump: O Contador de Histórias', 'A história de um homem simples e sua jornada extraordinária através de eventos históricos dos EUA.', 1994, 'https://m.media-amazon.com/images/I/61Kc8oZ3aKL._AC_SY679_.jpg', 'EUA', 142, 17, '12'),
('Fight Club', 'Clube da Luta', 'Um homem deprimido que sofre de insônia encontra um vendedor de sabonetes e juntos formam um clube de luta clandestino que evolui para algo muito maior.', 1999, 'https://rollingstone.com.br/media/_versions/brad-pitt-edward-norton-clube-da-luta-reprod_widelg.jpg', 'EUA', 139, 4, '18'),
('Inglourious Basterds', 'Bastardos Inglórios', 'Durante a Segunda Guerra Mundial, um grupo de soldados judeus americanos conhecidos como "Os Bastardos" espalha medo entre o Terceiro Reich ao realizar assassinatos brutais.', 2009, 'https://m.media-amazon.com/images/I/81tK5xXbQPL._AC_SY679_.jpg', 'DE', 153, 2, '18'),
('Coco', 'Viva: A Vida é uma Festa', 'Um jovem aspirante a músico embarca em uma jornada na Terra dos Mortos para descobrir a verdade sobre sua família e seu legado.', 2017, 'https://cinemacao.com/wp-content/uploads/2018/01/Viva-A-Vida-E-Uma-Festa-2.jpg', 'EUA', 105, 123, 'Livre'),
('Mad Max', 'Mad Max: Estrada da Fúria', 'Em um mundo pós-apocalíptico, Max ajuda um grupo de mulheres a escapar de um tirano que as mantém prisioneiras.', 2015, 'https://m.media-amazon.com/images/I/71j5Zy9v4cL._AC_SY679_.jpg', 'Austrália', 120, 124, '16'),
('The Social Network', 'A Rede Social', 'A história da criação do Facebook e a batalha judicial que se seguiu.', 2010, 'https://cptstatic.s3.amazonaws.com/imagens/enviadas/materias/materia13405/a-rede-social-cursos-cpt.jpg', 'EUA', 120, 4, '12'),
('The Grand Budapest Hotel', 'O Grande Hotel Budapeste', 'As aventuras de um concierge lendário em um famoso hotel europeu entre as guerras.', 2014, 'https://www.pjf.mg.gov.br/noticias/arquivo/18%2008%20Sessao%20Cidadao_175702.jpeg', 'HUN', 120, 125, '12'),
('The Shape of Water', 'A Forma da Água', 'Em um laboratório secreto do governo, uma zeladora muda se apaixona por uma criatura aquática presa.', 2017, 'https://ogimg.infoglobo.com.br/in/22353040-c59-70e/FT1500A/690/image.jpg', 'EUA', 120, 94, '16'),
('The Revenant', 'O Regresso', 'Um caçador de peles é deixado para morrer por seus companheiros após ser atacado por um urso. Ele sobrevive e parte em busca de vingança.', 2015, 'https://blogdescalada.com/critica-do-filme-o-regresso/critica-o-regresso-6/', 'EUA', 156, 92, '16'),
('Zootopia', 'Zootopia: Essa Cidade é o Bicho', 'Em uma cidade de animais antropomórficos, uma coelha policial e uma raposa trapaceira devem trabalhar juntas para desvendar uma conspiração.', 2016, 'https://cfnoticias.com.br/wp-content/uploads/2016/03/1-Zootopia-2.jpg', 'EUA', 108, 126, 'Livre');

INSERT INTO categorias_filmes (num_filme, id_categoria) VALUES
(1, 3),  
(1, 10),  
(1, 11),  
(2, 2),  
(2, 8),  
(2, 13),  
(3, 6),  
(3, 8),  
(3, 13),  
(3, 16),  
(4, 1),  
(4, 2),  
(4, 13),  
(4, 22),  
(5, 8),  
(5, 18),  
(5, 20),  
(6, 6),  
(6, 8),  
(6, 18),  
(7, 8),  
(7, 18),  
(8, 6),  
(8, 8),  
(8, 22),  
(9, 1),  
(9, 18),  
(9, 22),  
(10, 8),  
(10, 19),  
(11, 8),  
(11, 22),  
(12, 1),  
(12, 8),  
(12, 14),  
(12, 22),  
(13, 3),  
(13, 10),  
(13, 17),  
(14, 1),  
(14, 2),  
(14, 13),  
(15, 4),  
(15, 8),  
(16, 5),  
(16, 8),  
(17, 11),  
(17, 8),  
(17, 19),  
(18, 1),  
(18, 2),  
(18, 8),  
(18, 12),  
(19, 3),  
(19, 5),  
(19, 10);

INSERT INTO exibicao (num_filme, num_canal, data_exibicao) VALUES
(1, 7, '2024-09-18 00:00:00'),
(2, 12, '2024-09-18 04:30:00'),
(4, 10, '2024-09-25 10:30:00'),
(8, 4, '2024-09-30 15:00:00'),
(13, 13, '2024-10-08 16:30:00'),
(11, 7, '2024-10-01 08:30:00');
